### ISSUE TITLE
Module not found and URL error.

### ISSUE THREAD

**Issue by kunal-3196** [pyansys/pydpf-composites#201] opened 2023-02-05 06:26 UTC
### Before submitting the issue

- [X] I have visited the Troubleshooting section.
- [X] I have searched among the existing issues.
- [X] I am using a Python virtual environment.
- [X] I have a fully updated virtual environment (i.e. ``pip install --upgrade --upgrade-strategy eager ansys-mapdl-core``)

### Description of the bug
```
  File ~\untitled0.py:33 in <module>
    from ansys.dpf.composites.composite_model import CompositeModel

ModuleNotFoundError: No module named 'ansys.dpf.composites'
```

getting above error while running pyansys code

### Steps To Reproduce

Steps:
  * First I did...
  * Check the code from official pyansys website & copied it on Anaconda Spyder

  * ...

And I ran the following code:

```py

from ansys.mapdl.core import launch_mapdl
mapdl = launch_mapdl()

# Insert your code here
import ansys.dpf.core as dpf
import numpy as np

from ansys.dpf.composites.composite_model import CompositeModel
from ansys.dpf.composites.constants import Sym3x3TensorComponent
from ansys.dpf.composites.example_helper import get_continuous_fiber_example_files
from ansys.dpf.composites.layup_info.material_properties import MaterialProperty
from ansys.dpf.composites.select_indices import get_selected_indices
from ansys.dpf.composites.server_helpers import connect_to_or_start_server
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.9

### PyMAPDL Report

<details><summary>
Show the Report!
</summary>

```text

# PASTE HERE THE OUTPUT OF `python -c "from ansys.mapdl import core as pymapdl; print(pymapdl.Report())"` here
Traceback (most recent call last):

  File ~\untitled0.py:33 in <module>
    from ansys.dpf.composites.composite_model import CompositeModel

ModuleNotFoundError: No module named 'ansys.dpf.composites'
```
</details>

### Installed packages

<details><summary>
Show the installed packages!
</summary>

```text

# PASTE HERE THE OUTPUT OF `python -m pip freeze` here
Traceback (most recent call last):

  File ~\untitled0.py:33 in <module>
    from ansys.dpf.composites.composite_model import CompositeModel

ModuleNotFoundError: No module named 'ansys.dpf.composites'
```
</details>

### Logger output file

<details><summary>
Show the logger output file.
</summary>

```text
Also, below issue is there
# PASTE HERE THE CONTENT OF THE LOGGER OUTPUT FILE.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\LENOVO\\anaconda3\\Lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp39-win_amd64.pyd'
Consider using the `--user` option or check the permissions.
```
</details>

**Comment by greschd** [comment] 2023-02-20 17:04
@kunal-3196 the last error you posted definitely looks like a networking problem connecting to the Python package index, as @germa89 noted.

This could be temporary, in which case simply re-trying may work.

Otherwise, you can try 
```bash
ping files.pythonhosted.org
```
to ensure you have basic connectivity. The output should look similar to 
```
Pinging dualstack.r.ssl.global.fastly.net [151.101.129.63] with 32 bytes of data:
Reply from 151.101.129.63: bytes=32 time=5ms TTL=56
Reply from 151.101.129.63: bytes=32 time=5ms TTL=56
Reply from 151.101.129.63: bytes=32 time=6ms TTL=56
Reply from 151.101.129.63: bytes=32 time=5ms TTL=56

Ping statistics for 151.101.129.63:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 5ms, Maximum = 6ms, Average = 5ms
```

Have you been able to successfully install other packages with `pip install`? In principle, there's nothing special about `ansys-dpf-composites` in this step.

**Comment by greschd** [comment] 2023-02-21 09:06
@roosre AFAICT this is an installation problem / question, not a bug.

**Comment by kunal-3196** [comment] 2023-02-21 18:56
noted  thanks

**Comment by greschd** [comment] 2023-02-21 19:12
Yes, versions before 2023 R1 are not supported by PyDPF Composites.

However, this should not produce the same kind of error you were seeing. The Ansys version only comes into play when starting a DPF server, and loading the Composites plugin.

In other words,
```code
python -m pip install ansys-dpf-composites
python -c 'import ansys.dpf.composites'
```
should work with any of the supported Python versions (3.7+).

**Comment by greschd** [comment] 2023-02-25 21:05
This error occurs due to the `pyansys` meta-package (https://github.com/pyansys/pyansys). This is a collection of PyAnsys libraries, pinned to versions that are compatible. The meta-package is released once per Ansys release cycle.

Since `pydpf-composites` was released _after_ the last release of this meta-package, it is not included. The `ansys-dpf-core` and `ansys-dpf-gate` are still pinned to versions _older_ than what `pydpf-composites` needs.

For now, you can avoid this issue by uninstalling the meta-package:
```bash
pip uninstall pyansys
pip install ansys-dpf-composites
```
The packages that were originally included in the meta-package should not be uninstalled through this procedure.

From the next release of the `pyansys` meta-package, installing it will include `pydpf-composites` automatically.

**Comment by greschd** [comment] 2023-03-06 07:22
Yes, that is expected since the DPF Composites plug-in doesn't support earlier versions.

On the Python side, I think the module is now working as expected. I'll close this issue, but feel free to re-open it or create a new one in case you need more help.

**Closed by greschd** 2023-03-06 07:22 UTC
